/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CustomeTable: typeof import('./src/components/customTable/CustomeTable.vue')['default']
    HouzeoLogo: typeof import('./src/components/HouzeoLogo.vue')['default']
    NavigationDrawer: typeof import('./src/components/layouts/NavigationDrawer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Snackbar: typeof import('./src/components/snackbar/Snackbar.vue')['default']
    ToggleTheme: typeof import('./src/components/themeToggle/ToggleTheme.vue')['default']
    UserForm: typeof import('./src/components/UserForm.vue')['default']
  }
}
