/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/app/createWeeklyPlan': RouteRecordInfo<'/app/createWeeklyPlan', '/app/createWeeklyPlan', Record<never, never>, Record<never, never>>,
    '/app/editWeeklyPlan': RouteRecordInfo<'/app/editWeeklyPlan', '/app/editWeeklyPlan', Record<never, never>, Record<never, never>>,
    '/app/home': RouteRecordInfo<'/app/home', '/app/home', Record<never, never>, Record<never, never>>,
    '/app/project': RouteRecordInfo<'/app/project', '/app/project', Record<never, never>, Record<never, never>>,
    '/app/taskList': RouteRecordInfo<'/app/taskList', '/app/taskList', Record<never, never>, Record<never, never>>,
    '/app/viewWeeklyPlan': RouteRecordInfo<'/app/viewWeeklyPlan', '/app/viewWeeklyPlan', Record<never, never>, Record<never, never>>,
    '/app/weeklyPlans': RouteRecordInfo<'/app/weeklyPlans', '/app/weeklyPlans', Record<never, never>, Record<never, never>>,
    '/auth/login': RouteRecordInfo<'/auth/login', '/auth/login', Record<never, never>, Record<never, never>>,
    '/not-found': RouteRecordInfo<'/not-found', '/not-found', Record<never, never>, Record<never, never>>,
  }
}
