/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/app/home/project': RouteRecordInfo<'/app/home/project', '/app/home/project', Record<never, never>, Record<never, never>>,
    '/app/weeklyPlans/createWeeklyPlan': RouteRecordInfo<'/app/weeklyPlans/createWeeklyPlan', '/app/weeklyPlans/createWeeklyPlan', Record<never, never>, Record<never, never>>,
    '/app/weeklyPlans/editWeeklyPlan': RouteRecordInfo<'/app/weeklyPlans/editWeeklyPlan', '/app/weeklyPlans/editWeeklyPlan', Record<never, never>, Record<never, never>>,
    '/app/weeklyPlans/viewWeeklyPlan': RouteRecordInfo<'/app/weeklyPlans/viewWeeklyPlan', '/app/weeklyPlans/viewWeeklyPlan', Record<never, never>, Record<never, never>>,
    '/auth/login': RouteRecordInfo<'/auth/login', '/auth/login', Record<never, never>, Record<never, never>>,
    '/not-found': RouteRecordInfo<'/not-found', '/not-found', Record<never, never>, Record<never, never>>,
  }
}
